/*
 * Copyright 2023-2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v14.0
processor: MCXA153
package_id: MCXA153VLH
mcu_data: ksdk2_0
processor_version: 0.14.4
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
	BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '51', peripheral: LPUART0, signal: RX, pin_signal: P0_2/TDO/SWO/LPUART0_RXD/LPSPI0_SCK/CT0_MAT0/UTICK_CAP0/I3C0_PUR, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: '52', peripheral: LPUART0, signal: TX, pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/CMP0_OUT/CMP1_IN1, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
	/* Write to GPIO0: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GateGPIO0);
	/* Write to GPIO1: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GateGPIO1);
	/* Write to GPIO2: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GateGPIO2);
	/* Write to GPIO3: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GateGPIO3);
	/* Write to PORT0: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GatePORT0);
	/* Write to PORT1: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GatePORT1);
	/* Write to PORT2: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GatePORT2);
	/* Write to PORT3: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GatePORT3);
	/* GPIO0 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kGPIO0_RST_SHIFT_RSTn);
	/* GPIO1 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
	/* GPIO2 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
	/* GPIO3 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
	/* LPUART0 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kLPUART0_RST_SHIFT_RSTn);
	/* INPUTMUX0 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kINPUTMUX0_RST_SHIFT_RSTn);
	/* PORT0 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);
	/* PORT1 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
	/* PORT2 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
	/* PORT3 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);
	/* FLEXPWM0 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);

	const port_pin_config_t port0_2_pin51_config = {/* Internal pull-up resistor is enabled */
			kPORT_PullUp,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as LPUART0_RXD */
			kPORT_MuxAlt2,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT0_2 (pin 51) is configured as LPUART0_RXD */
	PORT_SetPinConfig(PORT0, 2U, &port0_2_pin51_config);

	const port_pin_config_t port0_3_pin52_config = {/* Internal pull-up resistor is enabled */
			kPORT_PullUp,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as LPUART0_TXD */
			kPORT_MuxAlt2,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT0_3 (pin 52) is configured as LPUART0_TXD */
	PORT_SetPinConfig(PORT0, 3U, &port0_3_pin52_config);

	const port_pin_config_t LED_GREEN = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_12 (pin 38) is configured as P3_12 */
	PORT_SetPinConfig(PORT3, 13U, &LED_GREEN);


	const port_pin_config_t port2_0_pin14_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT2_0 (pin 14) is configured as SF_B */
	PORT_SetPinConfig(PORT2, 0U, &port2_0_pin14_config);

	const port_pin_config_t port3_15_pin35_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_15 (pin 35) is configured as SLEW */
	PORT_SetPinConfig(PORT3, 15U, &port3_15_pin35_config);

	const port_pin_config_t port3_14_pin36_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_14 (pin 36) is configured as D2B */
	PORT_SetPinConfig(PORT3, 14U, &port3_14_pin36_config);

	const port_pin_config_t port2_6_pin20_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT2_6 (pin 20) is configured as INP_INV */
	PORT_SetPinConfig(PORT2, 6U, &port2_6_pin20_config);

	const port_pin_config_t port1_8_pin2_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT2_6 (pin 2) is configured as EN */
	PORT_SetPinConfig(PORT1, 8U, &port1_8_pin2_config);


	const port_pin_config_t port1_5_pin63_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT1_5 (pin 63) is configured as D1 */
	PORT_SetPinConfig(PORT1, 5U, &port1_5_pin63_config);


	port_pin_config_t port3_12_pin38_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt5,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_12 (pin 38) is configured as PWM1 */
	PORT_SetPinConfig(PORT3, 12U, &port3_12_pin38_config);

	port_pin_config_t port3_13_pin37_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_12 */
			kPORT_MuxAlt5,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_13 (pin 37) is configured as PWN2 */
	PORT_SetPinConfig(PORT3, 13U, &port3_13_pin37_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPI2C0_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '34', peripheral: LPI2C0, signal: SCL, pin_signal: P3_27/TRIG_OUT7/LPI2C0_SCL/CT_INP13, slew_rate: fast, open_drain: disable, drive_strength: low, drive_strength1: normal,
    pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: '33', peripheral: LPI2C0, signal: SDA, pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C0_SDA/CT_INP12, slew_rate: fast, open_drain: disable, drive_strength: low,
    drive_strength1: normal, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C0_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPI2C0_InitPins(void)
{
	/* Write to PORT3: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GatePORT3);
	/* PORT3 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

	const port_pin_config_t port3_27_pin34_config = {/* Internal pull-up resistor is enabled */
			kPORT_PullUp,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as LPI2C0_SCL */
			kPORT_MuxAlt2,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_27 (pin 34) is configured as LPI2C0_SCL */
	PORT_SetPinConfig(PORT3, 27U, &port3_27_pin34_config);

	const port_pin_config_t port3_28_pin33_config = {/* Internal pull-up resistor is enabled */
			kPORT_PullUp,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as LPI2C0_SDA */
			kPORT_MuxAlt2,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_28 (pin 33) is configured as LPI2C0_SDA */
	PORT_SetPinConfig(PORT3, 28U, &port3_28_pin33_config);
	const port_pin_config_t port1_13_pin7_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as TRIG_IN3 */
			kPORT_MuxAlt1,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT1_13 (pin 7) is configured as TRIG_IN3 */
	PORT_SetPinConfig(PORT1, 13U, &port1_13_pin7_config);

	const port_pin_config_t port1_6_pin64_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as TRIG_IN2 */
			kPORT_MuxAlt1,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT1_6 (pin 64) is configured as TRIG_IN2 */
	PORT_SetPinConfig(PORT1, 6U, &port1_6_pin64_config);

	const port_pin_config_t port3_0_pin46_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as TRIG_IN0 */
			kPORT_MuxAlt1,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_0 (pin 46) is configured as TRIG_IN0 */
	PORT_SetPinConfig(PORT3, 0U, &port3_0_pin46_config);

	const port_pin_config_t port3_1_pin45_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as TRIG_IN1 */
			kPORT_MuxAlt1,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_1 (pin 45) is configured as TRIG_IN1 */
	PORT_SetPinConfig(PORT3, 1U, &port3_1_pin45_config);

	const port_pin_config_t port2_0_pin14_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as ADC0_A0 */
			kPORT_MuxAlt0,
			/* Digital input disabled; it is required for analog functions */
			kPORT_InputBufferDisable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT2_0 (pin 14) is configured as ADC0_A0 */
	PORT_SetPinConfig(PORT2, 0U, &port2_0_pin14_config);


}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPI2C0_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '34', peripheral: GPIO3, signal: 'GPIO, 27', pin_signal: P3_27/TRIG_OUT7/LPI2C0_SCL/CT_INP13, slew_rate: fast, open_drain: disable, drive_strength: low,
    drive_strength1: normal, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '33', peripheral: GPIO3, signal: 'GPIO, 28', pin_signal: P3_28/WUU0_IN26/TRIG_IN11/LPI2C0_SDA/CT_INP12, slew_rate: fast, open_drain: disable, drive_strength: low,
    drive_strength1: normal, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C0_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPI2C0_DeinitPins(void)
{
	/* Write to PORT3: Peripheral clock is enabled */
	CLOCK_EnableClock(kCLOCK_GatePORT3);
	/* PORT3 peripheral is released from reset */
	RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

	const port_pin_config_t port3_27_pin34_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_27 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_27 (pin 34) is configured as P3_27 */
	PORT_SetPinConfig(PORT3, 27U, &port3_27_pin34_config);

	const port_pin_config_t port3_28_pin33_config = {/* Internal pull-up/down resistor is disabled */
			kPORT_PullDisable,
			/* Low internal pull resistor value is selected. */
			kPORT_LowPullResistor,
			/* Fast slew rate is configured */
			kPORT_FastSlewRate,
			/* Passive input filter is disabled */
			kPORT_PassiveFilterDisable,
			/* Open drain output is disabled */
			kPORT_OpenDrainDisable,
			/* Low drive strength is configured */
			kPORT_LowDriveStrength,
			/* Normal drive strength is configured */
			kPORT_NormalDriveStrength,
			/* Pin is configured as P3_28 */
			kPORT_MuxAlt0,
			/* Digital input enabled */
			kPORT_InputBufferEnable,
			/* Digital input is not inverted */
			kPORT_InputNormal,
			/* Pin Control Register fields [15:0] are not locked */
			kPORT_UnlockRegister};
	/* PORT3_28 (pin 33) is configured as P3_28 */
	PORT_SetPinConfig(PORT3, 28U, &port3_28_pin33_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
